# Services definition override for development

services:

  app:
    # Build override
    image: ${IMAGES_PREFIX:-app}-dev:${IMAGES_TAG:-latest}
    build:
      target: app_dev
    # Deploy override
    extra_hosts:
      - "host.docker.internal:host-gateway"
    develop:
      watch:
        # Docker image
        - action: rebuild
          path: ./app/Dockerfile
        # App source files
        - action: sync+restart
          path: ./app/app
          target: /app
          ignore:
            - node_modules/
