# Services overrides for testing

services:

  docs:
    # Extend
    extends:
      file: ./docker-compose-docs.yml
      service: docs
    # Build override
    image: ${IMAGES_PREFIX:-app}-docs-test-e2e:${IMAGES_TAG:-latest}
    build:
      target: app_test_e2e
      args:
        UID: ${DOCKER_UID:-${UID:-1000}}
    # Deploy override
    user: ${DOCKER_UID:-${UID:-1000}}
    environment:
      CI: ${CI:-}
    tmpfs:
      - /tmp:mode=1777,uid=${DOCKER_UID:-${UID:-1000}},gid=0
