# Services overrides for testing

name: cors-proxy-docs-test-unit

x-common:

  app-test-environment: &app-test-environment
    CI: ${CI:-}

services:

  docs:
    # Extend
    extends:
      file: ./docker-compose-docs.yml
      service: docs
    # Build override
    image: ${IMAGES_PREFIX:-app}-docs-test-unit:${IMAGES_TAG:-latest}
    build:
      target: test_unit
      args:
        UID: ${DOCKER_UID:-${UID:-1000}}
    # Deploy override
    user: ${DOCKER_UID:-${UID:-1000}}
    environment:
      <<: [ *app-test-environment ]
    tmpfs:
      - /tmp:mode=1777,exec,uid=${DOCKER_UID:-${UID:-1000}},gid=0
