# Services definition for building & deploying

x-common:

  docs:
    environment: &docs_environment
      GITHUB_REPOSITORY_URL: ${GITHUB_REPOSITORY_URL:-}
      GITHUB_SHA: ${GITHUB_SHA:-}

services:

  docs:
    # Build
    image: ${IMAGES_PREFIX:-app}-docs:${DOCKER_TAG:-latest}
    build:
      context: ./docs
      dockerfile: ./Dockerfile
      target: app_prod
      args:
        PORT: ${DOCS_DOCKER_PORT:-8080}
        <<: [ *docs_environment ]
    # Deploy
    environment:
      <<: [ *docs_environment ]
    ports:
      - "${DOCS_PORT:-80}:${DOCS_DOCKER_PORT:-8080}" # HTTP
