# Services definition for building & deploying

services:

  app:
    # Build
    image: ${IMAGES_PREFIX:-app}:${DOCKER_TAG:-latest}
    build:
      context: ./app
      dockerfile: ./Dockerfile
      target: app_prod
      args:
        PORT: ${APP_DOCKER_PORT:-8080}
    # Deploy
    ports:
      # HTTP
      - "${APP_PORT:-80}:${APP_DOCKER_PORT:-8080}"
