# Services definition for running npm commands

services:

  docs:
    # Extend
    extends:
      file: ./docker-compose-docs.yml
      service: docs
    # Build override
    image: ${IMAGES_PREFIX:-app}-npm:${DOCKER_TAG:-latest}
    build:
      target: app_npm
      args: !reset []
    # Deploy override
    environment: !reset []
    volumes:
      - ./docs/app:/app
    ports: !reset []
