# Services definition override for CI/CD

services:

  docs:
    # Build override
    image: ${IMAGES_PREFIX:-app}-docs-cicd:${IMAGES_TAG:-latest}
    build:
      target: app_prod_build
      args:
        BUILD_CHECK: ${BUILD_CHECK:-true}
    # Deploy override
    volumes:
      - ./docs/dist:/tmp/dist
    command: [ "sh", "-c", "rm -rf /tmp/dist/* && cp -r /app/dist/* /tmp/dist" ]
