# Services definition for building & deploying

services:

  proxy:
    # Build
    image: ${IMAGES_PREFIX:-app}:${IMAGES_TAG:-latest}
    build:
      context: ./proxy
      dockerfile: ./Dockerfile
      target: app_prod
      args:
        PORT: ${APP_DOCKER_PORT:-8080}
    # Deploy
    ports:
      - ${APP_PORT:-8080}:${APP_DOCKER_PORT:-8080} # HTTP
