name: Check Docs CI

on:

  # Run on pull requests to primary branches
  pull_request:
    branches:
      - master
      - main
      - prod
      - production
      - staging
      - dev
      - develop
      - development
      - test
    paths:
      - '.github/workflows/check.yml'
      - 'docs/**'
      - 'docker-compose-docs.yml'
      - 'docker-compose-docs.cicd.yml'

  # Run on manual triggers
  workflow_dispatch:

# Set GITHUB_TOKEN permissions for the workflow
permissions:
  contents: read

# Set workflow concurrency rules
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # Build Docs job
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build for production
        env:
          GITHUB_REPOSITORY_URL: https://github.com/${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          BUILD_CHECK: "true" # Run type checks
        run: docker compose -f docker-compose-docs.yml -f docker-compose-docs.cicd.yml build

      - name: Copy application files
        run: docker compose -f docker-compose-docs.yml -f docker-compose-docs.cicd.yml up

      - name: Check application files
        run: |
          [ -d ./docs/dist ] && [ $(ls -1 ./docs/dist | wc -l) -gt 0 ] \
            && echo "Application files found" \
            || ( echo "No application files found" && exit 1 )
