name: Push Docker CD

on:

  # Run on push on primary branches
  push:
    branches:
      - main
    paths:
      - '.github/workflows/push.yml'
      - 'app/**'
      - 'docker-compose.yml'

  # Run on manual triggers
  workflow_dispatch:

# Set GITHUB_TOKEN permissions for the workflow
permissions:
  contents: read

# Allow one concurrent deployment
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # Push Docker job
  push:
    name: Push Docker
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Set GITHUB_TOKEN permissions for the job
    permissions:
      contents: read
      packages: write

    # Set environment variables for the job
    env:
      REGISTRY: ghcr.io

    # Set outputs
    outputs:
      IMAGES_PREFIX: ${{ env.IMAGES_PREFIX }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Docker registry (GitHub Container Registry)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set IMAGES_PREFIX for GitHub Docker registry images
        env:
          REGISTRY: ${{ env.REGISTRY }}
          NAMESPACE: ${{ github.repository_owner }}
          IMAGES_NAME: ${{ github.event.repository.name }}
        run: |
          # Convert variables to lowercase
          REGISTRY="$(echo "${REGISTRY}" | tr '[:upper:]' '[:lower:]')"
          NAMESPACE="$(echo "${NAMESPACE}" | tr '[:upper:]' '[:lower:]')"
          IMAGES_NAME="$(echo "${IMAGES_NAME}" | tr '[:upper:]' '[:lower:]')"

          # Set IMAGES_PREFIX environment variable
          echo 'IMAGES_PREFIX<<DOCKER_ENV_EOF' >> $GITHUB_ENV
          echo "${REGISTRY}/${NAMESPACE}/${IMAGES_NAME}" >> $GITHUB_ENV
          echo 'DOCKER_ENV_EOF' >> $GITHUB_ENV

      - name: Pull latest Docker images for build cache
        env:
          IMAGES_PREFIX: ${{ env.IMAGES_PREFIX }}
          IMAGES_TAG: latest
        run: docker compose -f docker-compose.yml pull --ignore-pull-failures

      - name: Build Docker images for current commit (tag commit SHA)
        env:
          IMAGES_PREFIX: ${{ env.IMAGES_PREFIX }}
          IMAGES_TAG: ${{ github.sha }}
        run: docker compose -f docker-compose.yml build

      - name: Push Docker images for current commit (tag commit SHA)
        env:
          IMAGES_PREFIX: ${{ env.IMAGES_PREFIX }}
          IMAGES_TAG: ${{ github.sha }}
        run: docker compose -f docker-compose.yml push

      - name: Retag Docker images for main branch (tag 'latest')
        if: github.ref == 'refs/heads/main' # Only run on main branch
        env:
          IMAGES_PREFIX: ${{ env.IMAGES_PREFIX }}
          IMAGES_TAG: ${{ github.sha }}
          NEW_IMAGES_PREFIX: ${{ env.IMAGES_PREFIX }}
          NEW_IMAGES_TAG: latest
        run: |
          docker compose -f docker-compose.yml config --images | while read -r IMAGE; do
            echo "Retag '${IMAGE}' to '${NEW_IMAGES_PREFIX}:${NEW_IMAGES_TAG}'"
            docker tag "${IMAGE}" "${NEW_IMAGES_PREFIX}:${NEW_IMAGES_TAG}"
          done

      - name: Push Docker images for main branch (tag 'latest')
        if: github.ref == 'refs/heads/main' # Only run on main branch
        env:
          IMAGES_PREFIX: ${{ env.IMAGES_PREFIX }}
          IMAGES_TAG: latest
        run: docker compose -f docker-compose.yml push

  # Push Docker Hub job
  push-docker-hub:
    name: Push Docker Hub
    runs-on: ubuntu-latest
    timeout-minutes: 15

    needs:
      - push

    # Set GITHUB_TOKEN permissions for the job
    permissions:
      contents: read
      packages: read

    # Set environment variables for the job
    env:
      IMAGES_ORIGIN_PREFIX: ${{ needs.push.outputs.IMAGES_PREFIX }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set IMAGES_PREFIX for Docker Hub registry images
        env:
          NAMESPACE: ${{ vars.DOCKERHUB_USERNAME }}
          IMAGES_NAME: ${{ github.event.repository.name }}
        run: |
          # Convert variables to lowercase
          NAMESPACE="$(echo "${NAMESPACE}" | tr '[:upper:]' '[:lower:]')"
          IMAGES_NAME="$(echo "${IMAGES_NAME}" | tr '[:upper:]' '[:lower:]')"

          # Set IMAGES_PREFIX environment variable
          echo 'IMAGES_PREFIX<<DOCKER_ENV_EOF' >> $GITHUB_ENV
          echo "${NAMESPACE}/${IMAGES_NAME}" >> $GITHUB_ENV
          echo 'DOCKER_ENV_EOF' >> $GITHUB_ENV

      - name: Pull built Docker images from GitHub registry
        env:
          IMAGES_PREFIX: ${{ env.IMAGES_ORIGIN_PREFIX }}
          IMAGES_TAG: ${{ github.sha }}
        run: docker compose -f docker-compose.yml pull

      - name: Retag Docker images for Docker Hub (tag commit SHA)
        env:
          IMAGES_PREFIX: ${{ env.IMAGES_ORIGIN_PREFIX }}
          IMAGES_TAG: ${{ github.sha }}
          NEW_IMAGES_PREFIX: ${{ env.IMAGES_PREFIX }}
          NEW_IMAGES_TAG: ${{ github.sha }}
        run: |
          docker compose -f docker-compose.yml config --images | while read -r IMAGE; do
            echo "Retag '${IMAGE}' to '${NEW_IMAGES_PREFIX}:${NEW_IMAGES_TAG}'"
            docker tag "${IMAGE}" "${NEW_IMAGES_PREFIX}:${NEW_IMAGES_TAG}"
          done

      - name: Push Docker images for Docker Hub (tag commit SHA)
        env:
          IMAGES_PREFIX: ${{ env.IMAGES_PREFIX }}
          IMAGES_TAG: ${{ github.sha }}
        run: docker compose -f docker-compose.yml push

      - name: Retag Docker images for Docker Hub (tag 'latest')
        if: github.ref == 'refs/heads/main' # Only run on main branch
        env:
          IMAGES_PREFIX: ${{ env.IMAGES_ORIGIN_PREFIX }}
          IMAGES_TAG: ${{ github.sha }}
          NEW_IMAGES_PREFIX: ${{ env.IMAGES_PREFIX }}
          NEW_IMAGES_TAG: latest
        run: |
          docker compose -f docker-compose.yml config --images | while read -r IMAGE; do
            echo "Retag '${IMAGE}' to '${NEW_IMAGES_PREFIX}:${NEW_IMAGES_TAG}'"
            docker tag "${IMAGE}" "${NEW_IMAGES_PREFIX}:${NEW_IMAGES_TAG}"
          done

      - name: Push Docker images for Docker Hub (tag 'latest')
        if: github.ref == 'refs/heads/main' # Only run on main branch
        env:
          IMAGES_PREFIX: ${{ env.IMAGES_PREFIX }}
          IMAGES_TAG: latest
        run: docker compose -f docker-compose.yml push
